name: Deploy Lambda
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
 
      - name: Zip Lambda function code
        run: |
          zip lambda.zip lambda_function.py
 
      - name: Upload Lambda zip to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp lambda.zip s3://teamcity-dev-s3/lambda.zip
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
 
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform
 
      - name: Plan Terraform
        run: terraform plan -var-file="dev.tfvars"
        working-directory: ./terraform
 
      - name: Apply Terraform
        run: terraform apply -var-file="dev.tfvars" -auto-approve
        working-directory: ./terraform